name: Add to ProjectManagement board when issue created

on:
  issues:
    types: [opened]
env:
  MY_GITHUB_TOKEN: ${{ secrets.TANIRYO_SECRET_TOKEN }}

jobs:
  add-to-project-management:
    runs-on: ubuntu-latest
    steps:
    - name: Add to Project(ProjectManagement)
      uses: srggrs/assign-one-project-github-action@1.2.0
      with:
        project: 'https://github.com/users/taniryo-kun/projects/1'
